# Generated by Django 3.0.4 on 2021-06-02 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ddxlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abnormal_value', models.CharField(max_length=50)),
            ],
        ),
    ]
