# Generated by Django 3.0.4 on 2021-06-02 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello_ddx', '0002_auto_20210602_0236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Onedifferentiallist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('differential_list_one', models.CharField(max_length=50)),
                ('one_category', models.CharField(max_length=30)),
                ('one_true_up', models.BooleanField(default=False)),
                ('ddxlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello_ddx.Ddxlist')),
            ],
        ),
    ]
