# Generated by Django 3.0.4 on 2021-06-02 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_ddx', '0003_onedifferentiallist'),
    ]

    operations = [
        migrations.AddField(
            model_name='ddxlist',
            name='true_up',
            field=models.BooleanField(default=False),
        ),
    ]
