# Generated by Django 3.0.4 on 2021-06-02 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello_ddx', '0004_ddxlist_true_up'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firstddxlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('differential_list_first', models.CharField(max_length=50)),
                ('first_category', models.CharField(max_length=30)),
                ('first_true_up', models.BooleanField(default=False)),
                ('ddxlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello_ddx.Ddxlist')),
            ],
        ),
        migrations.CreateModel(
            name='Secondddxlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('differential_list_second', models.CharField(max_length=50)),
                ('second_category', models.CharField(max_length=30)),
                ('second_true_up', models.BooleanField(default=False)),
                ('firstddxlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello_ddx.Firstddxlist')),
            ],
        ),
        migrations.DeleteModel(
            name='Onedifferentiallist',
        ),
    ]
