# Generated by Django 3.0.4 on 2021-06-02 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello_ddx', '0005_auto_20210602_0341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firstddxlist',
            old_name='first_category',
            new_name='first_bt_category',
        ),
        migrations.RenameField(
            model_name='secondddxlist',
            old_name='second_category',
            new_name='second_bt_category',
        ),
    ]
