# Generated by Django 3.0.4 on 2021-06-02 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello_ddx', '0006_auto_20210602_0343'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thirdddxlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('differential_list_third', models.CharField(max_length=50)),
                ('third_bt_category', models.CharField(max_length=30)),
                ('third_true_up', models.BooleanField(default=False)),
                ('secondddxlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello_ddx.Secondddxlist')),
            ],
        ),
    ]
